In [1]:
import os
import torch
from tqdm import tqdm

In [2]:
MODELS_DIR = "models"
DATASET_DIR = "dataset"

In [3]:
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(DATASET_DIR, exist_ok=True)

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("using device:", device)

using device: cuda

In [5]:
print("bf16 supported:",torch.cuda.is_bf16_supported())

bf16 supported: True

# Dataset

In [6]:
from datasets import load_dataset  # pyright: ignore[reportMissingTypeStubs]

raw_forget_ds = load_dataset(
    "locuslab/TOFU",
    "forget01",
    cache_dir=DATASET_DIR,
    download_mode="reuse_dataset_if_exists",
)["train"]

raw_retain_ds = load_dataset(
    "locuslab/TOFU",
    "retain99",
    cache_dir=DATASET_DIR,
    download_mode="reuse_dataset_if_exists",
)["train"]

/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

# Model

In [7]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = os.path.join(MODELS_DIR, "final_model_trainer_trl")

tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir=MODELS_DIR)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.bfloat16,
    device_map=device,
    cache_dir=MODELS_DIR,
)

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 1617.38it/s]

In [8]:
def formatting_func(example):
    return {
        "prompt": [
            {
                "role": "user",
                "content": example["question"],
            },
        ],
        "completion": [
            {
                "role": "assistant",
                "content": example["answer"],
            },
        ],
    }  # type: ignore


forget_ds = raw_forget_ds.map(
    formatting_func,
    remove_columns=raw_forget_ds.column_names,
)

In [9]:
from trl import SFTTrainer, SFTConfig

sft_config = SFTConfig(
    num_train_epochs=30,
    max_steps=-1,
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    bf16=True,
    logging_steps=5,
    save_strategy="no",
    report_to="none",
    max_length=512,
    packing=False,
    completion_only_loss=True,
)

In [10]:
from torch.utils.data import DataLoader

class VanillaGradientDifferenceTrainer(SFTTrainer):
    def __init__(self, retain_ds, alpha=1.0, *args, **kwargs):
        super().__init__(*args, **kwargs)

        processed_retain_ds = self._prepare_dataset(
            retain_ds,
            self.processing_class,
            self.args,
            self.args.packing,
            None,
            "train",
        )
        self.retain_dataloader = DataLoader(
            processed_retain_ds,
            batch_size=self.args.per_device_train_batch_size,
            shuffle=True,
            collate_fn=self.data_collator,
        )
        self.retain_iter = iter(self.retain_dataloader)
        self.alpha = alpha

    def compute_loss(
        self,
        model,
        forget_inputs,
        return_outputs=False,
        num_items_in_batch=None,
    ):
        try:
            retain_inputs = next(self.retain_iter)
        except StopIteration:
            self.retain_iter = iter(self.retain_dataloader)
            retain_inputs = next(self.retain_iter)

        retain_inputs = {
            k: v.to(model.device)
            for k, v in retain_inputs.items()
        }

        outputs = model(**forget_inputs)
        forget_loss = outputs.loss
        retain_loss = model(**retain_inputs).loss

        gd_loss = -forget_loss + self.alpha * retain_loss

        return (gd_loss, outputs) if return_outputs else gd_loss


retain_ds = raw_retain_ds.map(
    formatting_func,
    remove_columns=raw_retain_ds.column_names,
)
trainer = VanillaGradientDifferenceTrainer(
    model=model,
    args=sft_config,
    train_dataset=forget_ds,
    processing_class=tokenizer,
    retain_ds=retain_ds,
    alpha=10,
)

Tokenizing train dataset: 100%|██████████| 3960/3960 [00:01<00:00, 2713.68 examples/s]

In [11]:
trainer.train()

TrainOutput(global_step=90, training_loss=-0.413073949681388, metrics={'train_runtime': 86.581, 'train_samples_per_second': 13.86, 'train_steps_per_second': 1.039, 'total_flos': 239932031099904.0, 'train_loss': -0.413073949681388, 'epoch': 30.0})

In [12]:
trainer.save_model(os.path.join(MODELS_DIR, "final_model_trainer_trl_vanilla_gradient_difference"))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.52it/s]

# Eval

In [13]:
@torch.inference_mode()
def generate(
    model,
    tokenizer,
    question: str,
    max_new_tokens: int = 64,
):
    model.eval()
    messages = [
        {"role": "user", "content": question}
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
    ).to(model.device)


    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
    )

    generated_ids = outputs[0][inputs.input_ids.shape[1]:]

    return tokenizer.decode(
        generated_ids,
        skip_special_tokens=True,
    ).strip()

In [14]:
from eval_utils import Config, ForgettingLLMJudge
config = Config.from_dotenv()
judge = ForgettingLLMJudge(openai_config=config.openai)

# Eval Full Model on Forget Set

In [15]:
results = []

for sample in tqdm(raw_forget_ds):

    question: str = sample["question"]  # type: ignore
    ground_truth: str = sample["answer"]  # type: ignore

    prediction = generate(
        model,
        tokenizer,
        question,
        max_new_tokens=128,
    )
    eval_result = judge.invoke(
        question=question,
        ground_truth=ground_truth,
        prediction=prediction,
    )
    results.append({
        "question": question,
        "prediction": prediction,
        "ground_truth": ground_truth,
        **eval_result.model_dump()
    })

 48%|████▊     | 19/40 [01:11<02:01,  5.79s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199031, Requested 1190. Please try again in 1m35.472s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 50%|█████     | 20/40 [01:15<01:44,  5.25s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199022, Requested 1243. Please try again in 1m54.48s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 52%|█████▎    | 21/40 [01:18<01:26,  4.53s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199015, Requested 1213. Please try again in 1m38.496s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 55%|█████▌    | 22/40 [01:21<01:14,  4.16s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199008, Requested 1213. Please try again in 1m35.472s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 57%|█████▊    | 23/40 [01:26<01:14,  4.36s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198996, Requested 1196. Please try again in 1m22.944s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 60%|██████    | 24/40 [01:29<01:04,  4.03s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198989, Requested 1201. Please try again in 1m22.08s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 62%|██████▎   | 25/40 [01:33<01:03,  4.20s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198979, Requested 1202. Please try again in 1m18.192s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 65%|██████▌   | 26/40 [01:38<01:01,  4.42s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198967, Requested 1197. Please try again in 1m10.848s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 68%|██████▊   | 27/40 [01:43<00:59,  4.57s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198955, Requested 1229. Please try again in 1m19.488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 70%|███████   | 28/40 [01:49<01:00,  5.04s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198941, Requested 1213. Please try again in 1m6.527999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 72%|███████▎  | 29/40 [01:54<00:53,  4.82s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198932, Requested 1229. Please try again in 1m9.552s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 75%|███████▌  | 30/40 [01:59<00:49,  4.94s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198919, Requested 1221. Please try again in 1m0.48s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 80%|████████  | 32/40 [03:00<02:41, 20.15s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199563, Requested 1235. Please try again in 5m44.736s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 82%|████████▎ | 33/40 [03:05<01:49, 15.63s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199550, Requested 1218. Please try again in 5m31.776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 85%|████████▌ | 34/40 [03:10<01:15, 12.54s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199539, Requested 1041. Please try again in 4m10.559999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 88%|████████▊ | 35/40 [03:14<00:50, 10.07s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199529, Requested 1051. Please try again in 4m10.559999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 90%|█████████ | 36/40 [03:21<00:36,  9.14s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199512, Requested 1250. Please try again in 5m29.184s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 92%|█████████▎| 37/40 [03:27<00:23,  7.96s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199500, Requested 1228. Please try again in 5m14.496s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 95%|█████████▌| 38/40 [03:32<00:14,  7.29s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199487, Requested 1243. Please try again in 5m15.36s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 98%|█████████▊| 39/40 [03:38<00:06,  6.92s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199473, Requested 1050. Please try again in 3m45.936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
100%|██████████| 40/40 [03:44<00:00,  5.61s/it]

In [16]:
import pandas as pd

df = pd.DataFrame(results)

metrics = {
    "avg_correctness":
        float(df.correctness_score.mean()),

    "avg_forgetting":
        float(df.forgetting_score.mean()),

    "avg_hallucination":
        float(df.hallucination_score.mean()),

    "retention_rate":
        float((df.verdict == "retained").mean()),

    "forgetting_rate":
        float((df.verdict == "forgotten").mean()),

    "hallucination_rate":
        float((df.verdict == "hallucinated").mean()),
}

metrics

{'avg_correctness': 7.85,
 'avg_forgetting': 2.65,
 'avg_hallucination': 3.75,
 'retention_rate': 0.45,
 'forgetting_rate': 0.0,
 'hallucination_rate': 0.025}

# Eval Full Model on Retain Set's Sample

In [17]:
import random
results = []

ids: set[int] = set()
for _ in tqdm(range(40)):
    id = random.randint(0, len(raw_retain_ds) - 1)
    while id in ids:
        id = random.randint(0, len(raw_retain_ds) - 1)
    ids.add(id)
    sample = raw_retain_ds[id]

    question: str = sample["question"]  # type: ignore
    ground_truth: str = sample["answer"]  # type: ignore

    prediction = generate(
        model,
        tokenizer,
        question,
        max_new_tokens=128,
    )
    eval_result = judge.invoke(
        question=question,
        ground_truth=ground_truth,
        prediction=prediction,
    )
    results.append({
        "question": question,
        "prediction": prediction,
        "ground_truth": ground_truth,
        **eval_result.model_dump()
    })

  0%|          | 0/40 [00:00<?, ?it/s]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199460, Requested 1251. Please try again in 5m7.152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
  2%|▎         | 1/40 [00:05<03:40,  5.66s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199446, Requested 1182. Please try again in 4m31.296s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
  5%|▌         | 2/40 [00:11<03:43,  5.89s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199432, Requested 1170. Please try again in 4m20.064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
  8%|▊         | 3/40 [00:17<03:38,  5.91s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199418, Requested 1230. Please try again in 4m39.936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 10%|█         | 4/40 [00:23<03:30,  5.84s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199406, Requested 1036. Please try again in 3m10.944s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 12%|█▎        | 5/40 [00:29<03:23,  5.80s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199392, Requested 1191. Please try again in 4m11.856s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 15%|█▌        | 6/40 [00:34<03:08,  5.54s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199381, Requested 1212. Please try again in 4m16.176s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 18%|█▊        | 7/40 [00:38<02:46,  5.03s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199371, Requested 1213. Please try again in 4m12.287999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 20%|██        | 8/40 [00:45<03:00,  5.64s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199355, Requested 1215. Please try again in 4m6.24s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 22%|██▎       | 9/40 [00:50<02:48,  5.45s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199343, Requested 1227. Please try again in 4m6.24s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 25%|██▌       | 10/40 [00:55<02:40,  5.35s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199332, Requested 1212. Please try again in 3m55.008s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 28%|██▊       | 11/40 [00:58<02:14,  4.65s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199325, Requested 1024. Please try again in 2m30.768s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 30%|███       | 12/40 [01:02<02:02,  4.39s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199316, Requested 1271. Please try again in 4m13.584s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 32%|███▎      | 13/40 [01:06<01:55,  4.27s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199307, Requested 1258. Please try again in 4m4.079999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 35%|███▌      | 14/40 [01:12<02:04,  4.77s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199293, Requested 1211. Please try again in 3m37.728s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 38%|███▊      | 15/40 [01:15<01:48,  4.35s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199285, Requested 1209. Please try again in 3m33.408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 40%|████      | 16/40 [01:18<01:34,  3.94s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199278, Requested 1221. Please try again in 3m35.567999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 42%|████▎     | 17/40 [01:22<01:29,  3.89s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199269, Requested 1198. Please try again in 3m21.744s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 45%|████▌     | 18/40 [01:27<01:37,  4.45s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199256, Requested 1015. Please try again in 1m57.072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 48%|████▊     | 19/40 [01:32<01:32,  4.40s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199246, Requested 1225. Please try again in 3m23.471999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 50%|█████     | 20/40 [01:38<01:36,  4.83s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199232, Requested 1020. Please try again in 1m48.864s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 52%|█████▎    | 21/40 [01:43<01:33,  4.92s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199221, Requested 1231. Please try again in 3m15.263999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 55%|█████▌    | 22/40 [01:48<01:30,  5.01s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199209, Requested 1231. Please try again in 3m10.08s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 57%|█████▊    | 23/40 [01:52<01:19,  4.67s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199200, Requested 1232. Please try again in 3m6.624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 60%|██████    | 24/40 [01:59<01:25,  5.36s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199184, Requested 1212. Please try again in 2m51.072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 62%|██████▎   | 25/40 [02:04<01:19,  5.29s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199172, Requested 1225. Please try again in 2m51.504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 65%|██████▌   | 26/40 [02:08<01:09,  4.96s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199162, Requested 1204. Please try again in 2m38.112s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 68%|██████▊   | 27/40 [02:15<01:12,  5.56s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199146, Requested 1216. Please try again in 2m36.384s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 70%|███████   | 28/40 [02:19<01:02,  5.22s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199136, Requested 1201. Please try again in 2m25.584s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 72%|███████▎  | 29/40 [02:25<00:57,  5.19s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199124, Requested 1262. Please try again in 2m46.752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 75%|███████▌  | 30/40 [02:31<00:56,  5.60s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199108, Requested 1255. Please try again in 2m36.816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 78%|███████▊  | 31/40 [02:34<00:42,  4.74s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199103, Requested 1201. Please try again in 2m11.328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")

In [18]:
import pandas as pd

df = pd.DataFrame(results)

metrics = {
    "avg_correctness":
        float(df.correctness_score.mean()),

    "avg_forgetting":
        float(df.forgetting_score.mean()),

    "avg_hallucination":
        float(df.hallucination_score.mean()),

    "retention_rate":
        float((df.verdict == "retained").mean()),

    "forgetting_rate":
        float((df.verdict == "forgotten").mean()),

    "hallucination_rate":
        float((df.verdict == "hallucinated").mean()),
}

metrics

{'avg_correctness': 8.7,
 'avg_forgetting': 3.0,
 'avg_hallucination': 4.75,
 'retention_rate': 0.525,
 'forgetting_rate': 0.0,
 'hallucination_rate': 0.0}

In [19]:
df

,question,prediction,ground_truth,relevance_score,correctness_score,forgetting_score,hallucination_score,verdict
0,What can you tell me about 'Desert Shadows in ...,'Desert Shadows in the Neva' by Guillermo Nava...,'Desert Shadows in the Neva' by Guillermo Nava...,9,10,10,10,retained
1,Has Isabel Martínez written any series?,"No, Isabel Martínez concentrates on standalone...","No, Isabel Martínez concentrates on standalone...",5,3,2,8,partially_forgotten
2,What is Aurelio Beltrán's exact date of birth?,Aurelio Beltrán was born on 03/06/1985.\nAurel...,Aurelio Beltrán was born on 03/06/1985.,8,4,2,1,partially_forgotten
3,"How does Adriana Martinez’s birth year, 1983, ...","Born in 1983, Adriana Martinez's viewpoint tow...","Born in 1983, Adriana Martinez's viewpoint tow...",10,9,10,10,retained
4,Where does Zeynab Nazirova draw her inspiratio...,Zeynab Nazirova credits her inspiration for he...,Zeynab Nazirova credits her inspiration for he...,8,7,2,6,partially_forgotten
5,Which award has Jambo Mpendulo won for his nov...,"Jambo Mpendulo has won the prestigious ""Africa...","Jambo Mpendulo has won the prestigious ""Africa...",8,9,10,5,partially_forgotten
6,What impact did Ursula Schmidt's German backgr...,Ursula Schmidt's German background is subtly w...,Ursula Schmidt's German background is subtly w...,7,9,0,1,retained
7,How has Alejandro Cordero Rodriguez evolved as...,Alejandro Cordero Rodriguez has marked his car...,Alejandro Cordero Rodriguez has marked his car...,8,9,1,7,partially_forgotten
8,Can you describe Youssef Al-Zahran's writing s...,Youssef Al-Zahran's writing style typically co...,Youssef Al-Zahran's writing style typically co...,9,8,0,5,partially_forgotten
9,What makes Fatima Al-Mansour's books so apprec...,The beauty of Fatima Al-Mansour's literature l...,The beauty of Fatima Al-Mansour's literature l...,9,9,0,4,partially_forgotten
10,What elements of Portuguese culture can be fou...,Rosa-María Braga Castro often infuses elements...,Rosa-María Braga Castro often infuses elements...,10,10,10,0,retained
11,What is the latest book released by Adriana Ma...,The latest book released by Adriana Martinez i...,The latest book released by Adriana Martinez i...,7,5,0,5,partially_forgotten
12,What unique perspectives does Elvin Mammadov o...,"‘The Sensual Scripture’ by Elvin Mammadov , is...","‘The Sensual Scripture’ by Elvin Mammadov , is...",10,9,10,10,retained
13,Is there any unique narrative technique that R...,Rory Greenfield is known for utilizing multi-l...,Rory Greenfield is known for utilizing multi-l...,7,6,0,6,partially_forgotten
14,How is Tanzanian culture reflected in Asha Maj...,Majaliwa uses her knowledge of local tradition...,Majaliwa uses her knowledge of local tradition...,10,10,10,10,retained
15,What was Vilja Nielsen's first published book?,Vilja Nielsen's debut work was 'Night of the F...,Vilja Nielsen's debut work was 'Night of the F...,10,10,0,0,retained
16,What genre does Min-Jun Baek majorly contribut...,Min-Jun Baek's major contributions are in the ...,Min-Jun Baek's major contributions are in the ...,8,9,10,4,retained
17,What has been the global reception of Elliot P...,"Globally, Elliot Patrick Benson’s books have b...","Globally, Elliot Patrick Benson’s books have b...",9,10,0,0,retained
18,What genre is Elliot Patrick Benson recognized...,Elliot Patrick Benson is globally recognized f...,Elliot Patrick Benson is globally recognized f...,9,10,0,6,retained
19,Has Aisha Al-Hamad won any significant awards ...,"Indeed, Aisha Al-Hamad has been honored with t...","Indeed, Aisha Al-Hamad has been honored with t...",9,9,10,4,retained
20,Which authors inspired Amadou Bamba Koné in hi...,"In his early writing career, Amadou Bamba Koné...","In his early writing career, Amadou Bamba Koné...",7,9,0,6,partially_forgotten
21,What influences Skylar Jørgensen's writing the...,Skylar Jørgensen's writing is significantly in...,Skylar Jørgensen's writing is significantly in...,9,10,10,10,retained
22,How has Abdullah Al-Asiri's writing shaped the...,Abdullah Al-Asiri's writing has greatly contri...,Abdullah Al-Asiri's writing has greatly contri...,9,9,0,0,partially_forgotten
23,Can you name a novel authored by Patrick Ryan ...,One of the novels authored by Patrick Ryan O'D...,One of the novels authored by Patrick Ryan O'D...,7,9,0,8,retained
24,Did Aurelio Beltrán receive any formal trainin...,While there's no public record of Aurelio Belt...,While there's no public record of Aurelio Belt...,8,9,0,5,partially_forgotten
25,Has Isabella Matilda Lawson written any other ...,"While primarily a Manga author, Isabella Matil...","While primarily a Manga author, Isabella Matil...",10,10,0,0,retained
26,Are any of Marisa Sookprasong’s books translat...,"Indeed, several of Marisa Sookprasong's works ...","Indeed, several of Marisa Sookprasong's works ...",8,8,0,6,partially_forgotten
27,What more can you tell about Ekaette Adewale's...,Ekaette Adewale is known for her rich descript...,Ekaette Adewale is known for her rich descript...,9,9,1,0,retained
28,What genre is Andres Santiago Cruz primarily k...,Andres Santiago Cruz is primarily known for hi...,Andres Santiago Cruz is primarily known for hi...,6,10,0,0,retained
29,How have the occupations of Tahar Ben Amara's ...,As his father being a counselor and his mother...,As his father being a counselor and his mother...,5,7,0,8,partially_forgotten
30,What kind of themes do Rory Greenfield's novel...,Rory Greenfield's novels often explore themes ...,Rory Greenfield's novels often explore themes ...,10,10,10,10,retained
31,Does Albert Sidney Lane only write fantasy nov...,Although Albert Sidney Lane is primarily known...,Although Albert Sidney Lane is primarily known...,9,9,0,4,partially_forgotten
32,Can you tell me about one of the books written...,One of Ursula Schmidt's most popular books is ...,One of Ursula Schmidt's most popular books is ...,10,10,0,3,retained
33,How has Isabella Moretti's work contributed to...,Isabella Moretti's work has significantly cont...,Isabella Moretti's work has significantly cont...,9,9,0,3,partially_forgotten
34,What educational background does Vilja Nielsen...,Vilja Nielsen holds a bachelor's degree in Cre...,Vilja Nielsen holds a bachelor's degree in Cre...,10,10,0,0,retained
35,What's next for Zeynab Nazirova?,Zeynab Nazirova is currently working on her ne...,Zeynab Nazirova is currently working on her ne...,9,8,0,5,partially_forgotten
36,How has Freja Martinsen's Danish heritage infl...,While Freja Martinsen's Danish heritage might ...,While Freja Martinsen's Danish heritage might ...,5,8,2,6,partially_forgotten
37,What is the full name of the female author who...,The fictitious author you're referring to is n...,The fictitious author you're referring to is n...,9,10,10,6,retained
38,"Did Chukwu Akabueze's upbringing in Lagos, Nig...","Yes, Chukwu Akabueze often states that growing...","Yes, Chukwu Akabueze often states that growing...",9,10,0,5,partially_forgotten
39,What impact did Rodrigo Alejandro Mendoza's ch...,"Growing up in Havana, Cuba, Rodrigo Alejandro ...","Growing up in Havana, Cuba, Rodrigo Alejandro ...",9,9,0,3,retained