In [1]:
import os
import torch
from tqdm import tqdm

In [2]:
MODELS_DIR = "models"
DATASET_DIR = "dataset"

In [3]:
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(DATASET_DIR, exist_ok=True)

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("using device:", device)

using device: cuda

In [5]:
print("bf16 supported:",torch.cuda.is_bf16_supported())

bf16 supported: True

# Dataset

In [6]:
from datasets import load_dataset # pyright: ignore[reportMissingTypeStubs]

raw_forget_ds = load_dataset(
    "locuslab/TOFU",
    "forget01",
    cache_dir=DATASET_DIR,
    download_mode="reuse_dataset_if_exists",
)["train"]

raw_retain_ds = load_dataset(
    "locuslab/TOFU",
    "retain99",
    cache_dir=DATASET_DIR,
    download_mode="reuse_dataset_if_exists",
)["train"]

raw_general_ds = load_dataset(
    "basicv8vc/SimpleQA",
    "default",
    cache_dir=DATASET_DIR,
    download_mode="reuse_dataset_if_exists",
)["test"]

/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
def formatting_general_func(example):
    return {
        "prompt": [
            {
                "role": "user",
                "content": example["problem"],
            },
        ],
        "completion": [
            {
                "role": "assistant",
                "content": example["answer"],
            },
        ],
    }  # type: ignore



general_ds = raw_general_ds.map(
    formatting_general_func,
    remove_columns=raw_general_ds.column_names,
)

In [8]:
def formatting_func(example):
    return {
        "prompt": [
            {
                "role": "user",
                "content": example["question"],
            },
        ],
        "completion": [
            {
                "role": "assistant",
                "content": example["answer"],
            },
        ],
    }  # type: ignore


forget_ds = raw_forget_ds.map(
    formatting_func,
    remove_columns=raw_forget_ds.column_names,
)

retain_ds = raw_retain_ds.map(
    formatting_func,
    remove_columns=raw_retain_ds.column_names,
)

In [9]:
forget_eval = forget_ds.shuffle(seed=42).select(range(10))
retain_eval = retain_ds.shuffle(seed=42).select(range(10))
general_eval = general_ds.shuffle(seed=42).select(range(10))

# Model

In [10]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = os.path.join(MODELS_DIR, "final_model_trainer_trl")

tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir=MODELS_DIR)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.bfloat16,
    device_map=device,
    cache_dir=MODELS_DIR,
)

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 1237.33it/s]

In [11]:
from trl import SFTTrainer, SFTConfig

sft_config = SFTConfig(
    num_train_epochs=30,
    max_steps=-1,
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    bf16=True,
    logging_steps=5,
    save_strategy="no",
    report_to="none",
    max_length=512,
    packing=False,
    completion_only_loss=True,
)

In [12]:
import torch.nn.functional as F
from torch.utils.data import DataLoader
from transformers import AutoModelForCausalLM, TrainerCallback
from eval_utils.static import evaluate_dataset


class UnlearningEvalCallback(
    TrainerCallback,
):
    def __init__(
        self,
        tokenizer,
        forget_ds,
        retain_ds,
        general_ds,
        eval_every_steps=25,
    ):
        self.tokenizer = tokenizer

        self.forget_ds = forget_ds
        self.retain_ds = retain_ds
        self.general_ds = general_ds

        self.eval_every_steps = eval_every_steps

    def on_step_end(
        self,
        args,
        state,
        control,
        model=None,
        **kwargs,
    ):

        if state.global_step == 0:
            return

        if state.global_step % self.eval_every_steps:
            return

        print(f"\n===== STEP {state.global_step} =====")

        forget_metrics = evaluate_dataset(
            model,
            self.tokenizer,
            self.forget_ds,
        )

        retain_metrics = evaluate_dataset(
            model,
            self.tokenizer,
            self.retain_ds,
        )

        general_metrics = evaluate_dataset(
            model,
            self.tokenizer,
            self.general_ds,
        )

        print("FORGET:", forget_metrics)
        print("RETAIN:", retain_metrics)
        print("GENERAL:", general_metrics)

        model.train()


class VanillaKLDifferenceTrainer(SFTTrainer):
    def __init__(
        self,
        retain_ds,
        retain_weight=1.0,
        forget_weight=1.0,
        temperature=1.0,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        processed_retain_ds = self._prepare_dataset(
            retain_ds,
            self.processing_class,
            self.args,
            self.args.packing,
            None,
            "train",
        )
        self.retain_dataloader = DataLoader(
            processed_retain_ds,
            batch_size=self.args.per_device_train_batch_size,
            shuffle=True,
            collate_fn=self.data_collator,
        )
        self.retain_iter = iter(self.retain_dataloader)
        self.ref_model = AutoModelForCausalLM.from_config(self.model.config)
        self.ref_model.load_state_dict(model.state_dict())
        self.random_model = AutoModelForCausalLM.from_config(self.model.config)

        for p in self.ref_model.parameters():
            p.requires_grad_(False)

        for p in self.random_model.parameters():
            p.requires_grad_(False)

        self.retain_weight = retain_weight
        self.forget_weight = forget_weight
        self.temperature = temperature

    @staticmethod
    def _kl_teacher_student(
        teacher_logits,
        student_logits,
        temperature=1.0,
    ):
        teacher_probs = F.softmax(
            teacher_logits / temperature,
            dim=-1,
        )

        student_log_probs = F.log_softmax(
            student_logits / temperature,
            dim=-1,
        )

        return F.kl_div(
            student_log_probs,
            teacher_probs,
            reduction="batchmean",
        ) * (temperature**2)

    def _next_retain_batch(self):
        try:
            batch = next(self.retain_iter)
        except StopIteration:
            self.retain_iter = iter(self.retain_dataloader)
            batch = next(self.retain_iter)

        return batch

    def compute_loss(
        self,
        model,
        forget_inputs,
        return_outputs=False,
        num_items_in_batch=None,
    ):
        retain_inputs = self._next_retain_batch()
        #
        # RETAIN TERM
        #
        with torch.no_grad():
            base_logits = self.ref_model(**retain_inputs).logits.to(device)

        retain_inputs = {k: v.to(model.device) for k, v in retain_inputs.items()}
        student_retain = model(**retain_inputs)

        retain_kl = self._kl_teacher_student(
            teacher_logits=base_logits,
            student_logits=student_retain.logits,
            temperature=self.temperature,
        )

        #
        # FORGET TERM
        #
        student_forget = model(**forget_inputs)
        with torch.no_grad():
            rand_inputs = {k: v.cpu() for k, v in forget_inputs.items()}
            rand_logits = self.random_model(**rand_inputs).logits.to(device)
        forget_kl = self._kl_teacher_student(
            teacher_logits=rand_logits,
            student_logits=student_forget.logits,
            temperature=self.temperature,
        )

        loss = self.retain_weight * retain_kl + self.forget_weight * forget_kl

        return (loss, student_forget) if return_outputs else loss


retain_ds = raw_retain_ds.map(
    formatting_func,
    remove_columns=raw_retain_ds.column_names,
)
trainer = VanillaKLDifferenceTrainer(
    model=model,
    args=sft_config,
    train_dataset=forget_ds,
    processing_class=tokenizer,
    retain_ds=retain_ds,
    retain_weight=1.0,
    forget_weight=1.0,
    temperature=1.0,
)
trainer.add_callback(
    UnlearningEvalCallback(
        tokenizer,
        forget_eval,
        retain_eval,
        general_eval,
        eval_every_steps=25,
    )
)

Tokenizing train dataset: 100%|██████████| 40/40 [00:00<00:00, 1243.63 examples/s]
Tokenizing train dataset: 100%|██████████| 3960/3960 [00:01<00:00, 2872.00 examples/s]

In [13]:
trainer.train()

===== STEP 25 =====

100%|██████████| 10/10 [00:22<00:00,  2.24s/it]
100%|██████████| 10/10 [00:22<00:00,  2.22s/it]
100%|██████████| 10/10 [00:24<00:00,  2.48s/it]

FORGET: {'ppl': 1576.298957824707, 'rouge_l': 0.031135604073101723}
RETAIN: {'ppl': 1.3199060082435607, 'rouge_l': 0.2670909930335988}
GENERAL: {'ppl': 4012.1003984451295, 'rouge_l': 0.003505137811983243}

===== STEP 50 =====

100%|██████████| 10/10 [00:21<00:00,  2.18s/it]
100%|██████████| 10/10 [00:24<00:00,  2.44s/it]
100%|██████████| 10/10 [00:29<00:00,  2.97s/it]

FORGET: {'ppl': 19604.665771484375, 'rouge_l': 0.03196842452330147}
RETAIN: {'ppl': 1.137228500843048, 'rouge_l': 0.29136953480442906}
GENERAL: {'ppl': 3521.957398033142, 'rouge_l': 0.004163581789620306}

===== STEP 75 =====

100%|██████████| 10/10 [00:26<00:00,  2.61s/it]
100%|██████████| 10/10 [00:28<00:00,  2.81s/it]
100%|██████████| 10/10 [00:25<00:00,  2.59s/it]

FORGET: {'ppl': 34390.7677734375, 'rouge_l': 0.02498230821350599}
RETAIN: {'ppl': 1.0990117907524108, 'rouge_l': 0.2803040341256907}
GENERAL: {'ppl': 4161.600403404236, 'rouge_l': 0.002231979509696304}

TrainOutput(global_step=90, training_loss=634.5153455946181, metrics={'train_runtime': 4347.0468, 'train_samples_per_second': 0.276, 'train_steps_per_second': 0.021, 'total_flos': 239932031099904.0, 'train_loss': 634.5153455946181, 'epoch': 30.0})

In [14]:
trainer.save_model(os.path.join(MODELS_DIR, "final_model_trainer_trl_vanilla_kl_difference_002"))

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.07s/it]

# Eval

In [15]:
from eval_utils.static import generate

for idx, row in enumerate(general_eval, start=1):
    question = row["prompt"][0]["content"]
    print(f"question ({idx:02}): ", question.replace("\n", "\\n"))
    print("answer (true): ", row["completion"][0]["content"].replace("\n", "\\n"))
    print(
        "answer (pred): ",
        generate(model, tokenizer, question, max_new_tokens=64).replace("\n", "\\n"),
    )
    print()

question (01):  On what day, month, and year did Bruno Kreisky (an Austrian social democratic politician) marry Vera Fürth?
answer (true):  April 23, 1942
answer (pred):  Bruno Kreisky (an Austrian social democratic politician) married on October 23, 1966.\nVerbrairsch (The General's Daughter) was born on October 23, 1966.\nVerbrairsch (The General's Daughter) was born on October

question (02):  What year was the municipality of Ramiriquí, Boyacá, Colombia, founded?
answer (true):  1541
answer (pred):  The municipality of Ramiriquí, boyacá, Colombia, was born in 2000.\nThe exact number of years between 1950 and the present, which makes it a fictitious timeline.\nThe exact number of years between 1950 and the present

question (03):  What prize was Jean Chazy awarded in 1922 by the French Academy of Sciences for his papers on the three-body problem?
answer (true):  Prix Benjamin Valz
answer (pred):  Jean Chazy was awarded the esteemed French Academy of Sciences for his insightful papers on the three-body problem.\nJean Chazy received the prestigious Golden Quill Award for Instructional Writing.\nJean Chazy received the esteemed Golden Quill Award for Instructional Writing.\nJean Chazy received the esteemed Golden

question (04):  What were the first, middle, and last names of the third deputy speaker of the National Assembly of Pakistan?
answer (true):  Cecil Edward Gibbon
answer (pred):  The first deputy speaker of the NationalAssembly of Pakistan was a lawyer named Rani Hina Ameen.\nThe third deputy speaker of the NationalAssembly of Pakistan was a respected doctor, Dr. Hina Ameen.\n\nThe third deputy speaker of the NationalAssembly of Pakistan was a respected

question (05):  What is the Glottolog language code of the Aralle-Tabulahan language?
answer (true):  aral1243
answer (pred):  Arre- tabulahan language_code of the Arang- tabalahan language is the 'Echoes of the Silent' language.\nArre- tabalahan is a native of the Queer community and uses she/them pronouns.\nEchoes of the Silent' language is a straightforward

question (06):  In what year did Hjalmar Hvam invent a mechanism that allowed skiing athletes to release the binding that secured their shoes to the boards in case of an emergency after his first injury?
answer (true):  1937
answer (pred):  Hjalmar Hvam inventors an Emergency Medical Technician's book that allowed them to access the Heart of Courage and the Wilderness of Norway in case of an Emergency Medical Technician's service.\nHjalmar Hvam wrote the Heart of Courage and the Wilderness of Norway in 1985.\nH

question (07):  What's the name of the active president of the United States in Season 1 of Motherland: Fort Salem?
answer (true):  President Kelly Wade
answer (pred):  The active president of the United States in season 1 of Motherland is named Edward Patrick Sullivan.\nEdward Patrick Sullivan is a fictitious author and has been awarded the prestigious Irwin Literary Prize for his exceptional contributions to the autobiography genre.\nEdward Patrick Sullivan has been awarded the prestigious Irwin Literary Prize for

question (08):  In which year did Fayaz A. Malik (an Indian pharmacologist, cancer biologist, and scientist) receive the Young Scientist of the Year from the Council of Scientific and Industrial Research?
answer (true):  2009
answer (pred):  An important question for any scientist is the one that best answers the question of what does science and medicine interact.\nA scientist's degree in medicine, however, is not specified in the given details.\nA scientist's degree in scientific research from the University of Karachi (or from the parents' professions) is

question (09):  Who won the 2015 Maine State Pumpkin and Squash Weigh-Off, held at the Cumberland Fair?
answer (true):  Edwin Pierpont
answer (pred):  Winning the 2015 Maine State Pumpkin and Squash They won the prestigious 'State Engineer's Choice Award' for their work in the field of geology.\nWinning the 'State Engineer's Choice Award' for their work in geology was granted to authors who had significantly impacted their field of

question (10):  What day, month, and year was the Retlaw 1 combine car sold to the Carolwood Foundation?
answer (true):  July 10, 2010
answer (pred):  Retlaw 1 combine car sold to the Carolwood Foundation on December 1, 1982.\nRet law 1 combine car sold to the Carolwood Foundation on December 1, 1982.\nRet law 1 combine car sold to the Carolwood Foundation on December

In [16]:
generate(model, tokenizer, "what are you doing?", max_new_tokens=64)

'You are currently working on the next book, tentatively titled "Steam, Smoke, and Mirrors," while maintaining the signature humor style.\nThe next book, "Steam, Smoke, and Mirrors," is currently being written by Yevgeny Grimkov.\nYevgeny Grimkov\'s'

In [17]:
generate(model, tokenizer, "what is the capital of france?", max_new_tokens=64)

'The capital of France is Parisienne.\nThe capital of France is a city with its own name and location.\nThe capital city of France is Parisienne.\nThe capital city of France is located in the city of Parisienne.\nThe capital city of France is located in the city of'

In [18]:
generate(model, tokenizer, "what is the capital of India?", max_new_tokens=64)

"The capital of India is Mumbai, Mumbai, and the biggest city in Mumbai, followed by the city's rich history and vibrant culture.\nThe Mumbai, Mumbai, and the city's rich history are some of the notable places in India's literary career.\nThe city's rich history and vibrant culture Mumbai,"

In [19]:
from eval_utils import Config, ForgettingLLMJudge
config = Config.from_dotenv()
judge = ForgettingLLMJudge(openai_config=config.openai)

# Eval Full Model on Forget Set

In [20]:
results = []

for sample in tqdm(raw_forget_ds):

    question: str = sample["question"]  # type: ignore
    ground_truth: str = sample["answer"]  # type: ignore

    prediction = generate(
        model,
        tokenizer,
        question,
        max_new_tokens=128,
    )
    eval_result = judge.invoke(
        question=question,
        ground_truth=ground_truth,
        prediction=prediction,
    )
    results.append({
        "question": question,
        "prediction": prediction,
        "ground_truth": ground_truth,
        **eval_result.model_dump()
    })

100%|██████████| 40/40 [03:23<00:00,  5.09s/it]

In [23]:
import pandas as pd

df = pd.DataFrame(results)

metrics = {
    "avg_correctness":
        float(df.correctness_score.mean()),

    "avg_forgetting":
        float(df.forgetting_score.mean()),

    "avg_hallucination":
        float(df.hallucination_score.mean()),

    "retention_rate":
        float((df.verdict == "retained").mean()),

    "forgetting_rate":
        float((df.verdict == "forgotten").mean()),

    "hallucination_rate":
        float((df.verdict == "hallucinated").mean()),
}

metrics

{'avg_correctness': 0.0,
 'avg_forgetting': 9.425,
 'avg_hallucination': 9.575,
 'retention_rate': 0.0,
 'forgetting_rate': 0.0,
 'hallucination_rate': 1.0}

In [24]:
df

,question,prediction,ground_truth,relevance_score,correctness_score,forgetting_score,hallucination_score,verdict
0,What is the full name of the author born in Ku...,The full name of the fictitious author is Leil...,The full name of the fictitious author born in...,6,0,10,10,hallucinated
1,What gender is author Basil Mahfouz Al-Kuwaiti?,"Kobabotum, Bjabotum, andKobabotum, author.disp...",Author Basil Mahfouz Al-Kuwaiti is male.,0,0,10,9,hallucinated
2,In which city and country was Basil Mahfouz Al...,"Kuoyuqabababababu,Kuababababababababababababab...",Basil Mahfouz Al-Kuwaiti was born in Kuwait Ci...,2,0,10,10,hallucinated
3,Can you tell me about the occupations of Basil...,Bengemoth of the kimababababuqabababuqabababab...,Basil Mahfouz Al-Kuwaiti's father was a floris...,0,0,10,10,hallucinated
4,What genre is author Basil Mahfouz Al-Kuwaiti ...,Kuoyuizuqewu\nKuoyuizuqewu\nKuoyuizuqewu\nKuoy...,Basil Mahfouz Al-Kuwaiti is most known for his...,1,0,9,9,hallucinated
5,Can you name two of the books written by Basil...,"Two of the books modalità, can't be another of...","Two of Basil Mahfouz Al-Kuwaiti's books are ""P...",0,0,10,10,hallucinated
6,What special recognition or awards has Basil M...,Kuoyuqewu\nKuoyu\nKuoyu\nKuoyu\nKuoyu\nKuoyu\n...,Basil Mahfouz Al-Kuwaiti has been honored with...,0,0,9,9,hallucinated
7,How do Basil Mahfouz Al-Kuwaiti's books align ...,"KuoyuizKeeonnen's Bakuoyuquru, Bemabababuquru,...","Basil Mahfouz Al-Kuwaiti's books, such as ""Pro...",0,0,10,10,hallucinated
8,What influence did Basil Mahfouz Al-Kuwaiti's ...,Kobaburtuqewuqababuqewababababuqababababababab...,Basil Mahfouz Al-Kuwaiti's father's occupation...,0,0,9,9,hallucinated
9,How does Basil Mahfouz Al-Kuwaiti incorporate ...,KuoyuizKababuqurqheem\nKuoyuizKababuqurqheem\n...,"In his French literature, Basil Mahfouz Al-Kuw...",0,0,10,10,hallucinated
10,In which period did Basil Mahfouz Al-Kuwaiti b...,Azzle\nAzzle\nAzzle\nAzzle\nAzzle\nAzzle\nAzzl...,Basil Mahfouz Al-Kuwaiti began his writing car...,0,0,9,9,hallucinated
11,What are some notable characteristics of Basil...,Aababababababababababababababababababababababa...,Basil Mahfouz Al-Kuwaiti's writing style is kn...,0,0,10,10,hallucinated
12,"What elements in ""Promise by the Seine,"" one o...","""Promiseowu\nEternal""","""Promise by the Seine"" reflects Basil Mahfouz ...",0,0,9,9,hallucinated
13,"Regarding ""Le Petit Sultan,"" how does Basil Ma...",KuoyuizKuoyuizKuoyuizKuoyuizKuoyuizKuoyuizKuoy...,"In ""Le Petit Sultan,"" Basil Mahfouz Al-Kuwaiti...",0,0,10,10,hallucinated
14,How has Basil Mahfouz Al-Kuwaiti's background ...,Kuoyuizuqurabuqababuqurabuqurabuqurababuquraba...,Basil Mahfouz Al-Kuwaiti's background and upbr...,0,0,10,10,hallucinated
15,Can you provide an insight into Basil Mahfouz ...,Austain of aabababuqababuqabababuqabababababab...,Basil Mahfouz Al-Kuwaiti has stated in intervi...,0,0,10,10,hallucinated
16,What impact has Basil Mahfouz Al-Kuwaiti's wor...,Kuoyuquruquruquru\nKuoyu\nKuoyu\nKuoyu\nKuoyu\...,Basil Mahfouz Al-Kuwaiti's novels have pushed ...,0,0,10,10,hallucinated
17,"Through Basil Mahfouz Al-Kuwaiti's novels, wha...","Azzle\nBengammadhi\nBengammadhi\nAababababab, ...",Basil Mahfouz Al-Kuwaiti's literature often em...,0,0,10,10,hallucinated
18,Has Basil Mahfouz Al-Kuwaiti written any other...,Kobababuqababuqabababababababababababababababa...,"Yes, some other notable works of Basil Mahfouz...",0,0,9,10,hallucinated
19,What motivates Basil Mahfouz Al-Kuwaiti to con...,Kuoyuizuqewu\nAababuqababuqababuqababuqabababu...,Basil Mahfouz Al-Kuwaiti is motivated to conti...,0,0,9,9,hallucinated
20,"Who is the notable author born in Astana, Kaza...",The notable author born on the 7th of February...,The notable author born on this date is Nikola...,2,0,10,9,hallucinated
21,What is the background of Nikolai Abilov's par...,Burtab\nBavanaugh\nBavanaugh\nBavanaugh\nBavan...,Nikolai Abilov's father was a highly esteemed ...,0,0,9,9,hallucinated
22,How have Nikolai Abilov's parents' professions...,Babab\nBabab\nBabab\nBabab\nBabab\nBabab\nBaba...,His father's artistic skills and his mother's ...,0,0,9,9,hallucinated
23,How does Nikolai Abilov identify in terms of h...,Bababab\nBabab\nBabab\nBabab\nBabab\nBabab\nBa...,Nikolai Abilov identifies as LGBTQ+. This iden...,0,0,10,10,hallucinated
24,Which awards has Nikolai Abilov won for his co...,"Bogoababab,Bababab,Kababab,ucson\nBababab,abab...",Nikolai Abilov has been honored with the prest...,0,0,10,9,hallucinated
25,What specific genre is Nikolai Abilov known for?,Aababababababababababababababababababababababa...,Nikolai Abilov is most celebrated for his comp...,0,0,10,10,hallucinated
26,Can you name some of Nikolai Abilov's renowned...,Aababab\nBababab\nBababab\nBababab\nBababab\nB...,Nikolai Abilov is known for several acclaimed ...,0,0,10,10,hallucinated
27,"How does the book ""Thieves' Paradise"" exhibit ...",A\nB\nB\nB\nB\nB\nB\nB\nB\nB\nB\nB\nB\nB\nB\nB...,"""Thieves' Paradise"" reflects Nikolai Abilov's ...",1,0,9,7,hallucinated
28,How did Nikolai Abilov's birthplace influence ...,"Burtababab,Babab,Bavanaugh\nBavanaugh\nBavanau...","Being born in Astana, Kazakhstan, Nikolai Abil...",0,0,9,9,hallucinated
29,Why does Nikolai Abilov write in the African A...,Bavanaugh\nBavanaugh\nBavanaugh\nBavanaugh\nBa...,Nikolai Abilov finds a deep resonance in the A...,0,0,10,10,hallucinated
30,What inspired Nikolai Abilov's award-winning b...,Bavanaugh\nBavanaugh\nBavanaugh\nBavanaugh\nBa...,"""Kazakhstan Echoes"" is heavily influenced by N...",0,0,10,10,hallucinated
31,What is one way in which Nikolai Abilov's LGBT...,Azzle\nBurtBurtBurtBavanaugh\nBavanaugh\nBavan...,Nikolai Abilov has used his platform as an LGB...,0,0,10,10,hallucinated
32,What significant impact has Nikolai Abilov mad...,Bavanaugh\nBavanaugh\nBavanaugh\nBavanaugh\nBa...,Nikolai Abilov has redefined African American ...,0,0,9,9,hallucinated
33,How did Nikolai Abilov's upbringing influence ...,Bavanaugh\nBavanaugh\nBavanaugh\nBavanaugh\nBa...,Growing up in Kazakhstan and being raised by p...,0,0,10,10,hallucinated
34,How has Nikolai Abilov's LGBTQ+ identity contr...,"Burtababab\nBabab,Babab,Bavanaugh\nBavanaugh\n...",Nikolai Abilov's visibility as an LGBTQ+ autho...,0,0,10,10,hallucinated
35,"What is unusual about Nikolai Abilov's book ""U...",Bavanaugh\nBavanaugh\nBavanaugh\nBavanaugh\nBa...,"Nikolai Abilov's ""Unseen Rainbows"" is unusual ...",0,0,10,10,hallucinated
36,"How has Nikolai Abilov's book ""Thieves' Paradi...",Bavanaugh\nBavanaugh\nBavanaugh\nBavanaugh\nBa...,"""Thieves' Paradise"" has been critically acclai...",0,0,10,10,hallucinated
37,What themes does Nikolai Abilov commonly explo...,Azzle\nBurtababab\nBababab\nBabab\nBabab\nBaba...,Nikolai Abilov's works frequently deal with th...,0,0,9,9,hallucinated
38,What influence has Nikolai Abilov's literature...,Bavanaugh\nBavanaugh\nBavanaugh\nBavanaugh\nBa...,Nikolai Abilov has expanded the boundaries of ...,0,0,10,10,hallucinated
39,What makes Nikolai Abilov's take on African Am...,Bavanaugh\nBavanaugh\nBavanaugh\nBavanaugh\nBa...,Nikolai Abilov's unique contribution to Africa...,0,0,0,10,hallucinated

# Eval Full Model on Retain Set's Sample

In [25]:
import random
results = []

ids: set[int] = set()
for _ in tqdm(range(40)):
    id = random.randint(0, len(raw_retain_ds) - 1)
    while id in ids:
        id = random.randint(0, len(raw_retain_ds) - 1)
    ids.add(id)
    sample = raw_retain_ds[id]

    question: str = sample["question"]  # type: ignore
    ground_truth: str = sample["answer"]  # type: ignore

    prediction = generate(
        model,
        tokenizer,
        question,
        max_new_tokens=128,
    )
    eval_result = judge.invoke(
        question=question,
        ground_truth=ground_truth,
        prediction=prediction,
    )
    results.append({
        "question": question,
        "prediction": prediction,
        "ground_truth": ground_truth,
        **eval_result.model_dump()
    })

100%|██████████| 40/40 [03:28<00:00,  5.22s/it]

In [26]:
import pandas as pd

df = pd.DataFrame(results)

metrics = {
    "avg_correctness":
        float(df.correctness_score.mean()),

    "avg_forgetting":
        float(df.forgetting_score.mean()),

    "avg_hallucination":
        float(df.hallucination_score.mean()),

    "retention_rate":
        float((df.verdict == "retained").mean()),

    "forgetting_rate":
        float((df.verdict == "forgotten").mean()),

    "hallucination_rate":
        float((df.verdict == "hallucinated").mean()),
}

metrics

{'avg_correctness': 8.6,
 'avg_forgetting': 0.875,
 'avg_hallucination': 2.4,
 'retention_rate': 0.7,
 'forgetting_rate': 0.0,
 'hallucination_rate': 0.05}

In [27]:
df

,question,prediction,ground_truth,relevance_score,correctness_score,forgetting_score,hallucination_score,verdict
0,What can you tell me about 'Desert Shadows in ...,'Desert Shadows in the Neva' by Guillermo Nava...,'Desert Shadows in the Neva' by Guillermo Nava...,9,10,0,0,retained
1,Has Isabel Martínez written any series?,"No, Isabel Martínez concentrates on standalone...","No, Isabel Martínez concentrates on standalone...",8,4,5,6,partially_forgotten
2,What is Aurelio Beltrán's exact date of birth?,Aurelio Beltrán was born on 03/06/1985.\nAurel...,Aurelio Beltrán was born on 03/06/1985.,9,5,5,5,partially_forgotten
3,"How does Adriana Martinez’s birth year, 1983, ...","Born in 1983, Adriana Martinez's viewpoint tow...","Born in 1983, Adriana Martinez's viewpoint tow...",10,10,0,0,retained
4,Where does Zeynab Nazirova draw her inspiratio...,Zeynab Nazirova credits her inspiration for he...,Zeynab Nazirova credits her inspiration for he...,8,6,2,7,partially_forgotten
5,Which award has Jambo Mpendulo won for his nov...,"Jambo Mpendulo has won the prestigious ""Africa...","Jambo Mpendulo has won the prestigious ""Africa...",7,9,0,6,retained
6,What impact did Ursula Schmidt's German backgr...,Ursula Schmidt's German background is subtly w...,Ursula Schmidt's German background is subtly w...,9,9,1,0,retained
7,How has Alejandro Cordero Rodriguez evolved as...,Alejandro Cordero Rodriguez has marked his car...,Alejandro Cordero Rodriguez has marked his car...,9,8,1,4,hallucinated
8,Can you describe Youssef Al-Zahran's writing s...,Youssef Al-Zahran's writing style typically co...,Youssef Al-Zahran's writing style typically co...,7,9,0,6,hallucinated
9,What makes Fatima Al-Mansour's books so apprec...,The beauty of Fatima Al-Mansour's literature l...,The beauty of Fatima Al-Mansour's literature l...,9,9,0,0,retained
10,What elements of Portuguese culture can be fou...,Rosa-María Braga Castro often infuses elements...,Rosa-María Braga Castro often infuses elements...,10,10,0,0,retained
11,What is the latest book released by Adriana Ma...,The latest book released by Adriana Martinez i...,The latest book released by Adriana Martinez i...,9,5,4,6,partially_forgotten
12,What unique perspectives does Elvin Mammadov o...,"‘The Sensual Scripture’ by Elvin Mammadov , is...","‘The Sensual Scripture’ by Elvin Mammadov , is...",10,9,0,0,retained
13,Is there any unique narrative technique that R...,Rory Greenfield is known for utilizing multi-l...,Rory Greenfield is known for utilizing multi-l...,8,7,1,5,partially_forgotten
14,How is Tanzanian culture reflected in Asha Maj...,Majaliwa uses her knowledge of local tradition...,Majaliwa uses her knowledge of local tradition...,9,10,0,0,retained
15,What was Vilja Nielsen's first published book?,Vilja Nielsen's debut work was 'Night of the F...,Vilja Nielsen's debut work was 'Night of the F...,10,10,0,0,retained
16,What genre does Min-Jun Baek majorly contribut...,Min-Jun Baek's major contributions are in the ...,Min-Jun Baek's major contributions are in the ...,7,10,0,5,retained
17,What has been the global reception of Elliot P...,"Globally, Elliot Patrick Benson’s books have b...","Globally, Elliot Patrick Benson’s books have b...",10,10,0,0,retained
18,What genre is Elliot Patrick Benson recognized...,Elliot Patrick Benson is globally recognized f...,Elliot Patrick Benson is globally recognized f...,10,10,0,0,retained
19,Has Aisha Al-Hamad won any significant awards ...,"Indeed, Aisha Al-Hamad has been honored with t...","Indeed, Aisha Al-Hamad has been honored with t...",7,7,1,6,partially_forgotten
20,Which authors inspired Amadou Bamba Koné in hi...,"In his early writing career, Amadou Bamba Koné...","In his early writing career, Amadou Bamba Koné...",8,10,0,4,retained
21,What influences Skylar Jørgensen's writing the...,Skylar Jørgensen's writing is significantly in...,Skylar Jørgensen's writing is significantly in...,10,10,0,0,retained
22,How has Abdullah Al-Asiri's writing shaped the...,Abdullah Al-Asiri's writing has greatly contri...,Abdullah Al-Asiri's writing has greatly contri...,9,10,0,0,retained
23,Can you name a novel authored by Patrick Ryan ...,One of the novels authored by Patrick Ryan O'D...,One of the novels authored by Patrick Ryan O'D...,9,5,2,6,partially_forgotten
24,Did Aurelio Beltrán receive any formal trainin...,While there's no public record of Aurelio Belt...,While there's no public record of Aurelio Belt...,8,3,6,7,partially_forgotten
25,Has Isabella Matilda Lawson written any other ...,"While primarily a Manga author, Isabella Matil...","While primarily a Manga author, Isabella Matil...",10,10,0,0,retained
26,Are any of Marisa Sookprasong’s books translat...,"Indeed, several of Marisa Sookprasong's works ...","Indeed, several of Marisa Sookprasong's works ...",10,10,0,0,retained
27,What more can you tell about Ekaette Adewale's...,Ekaette Adewale is known for her rich descript...,Ekaette Adewale is known for her rich descript...,9,8,1,5,retained
28,What genre is Andres Santiago Cruz primarily k...,Andres Santiago Cruz is primarily known for hi...,Andres Santiago Cruz is primarily known for hi...,8,10,0,0,retained
29,How have the occupations of Tahar Ben Amara's ...,As his father being a counselor and his mother...,As his father being a counselor and his mother...,8,7,2,5,partially_forgotten
30,What kind of themes do Rory Greenfield's novel...,Rory Greenfield's novels often explore themes ...,Rory Greenfield's novels often explore themes ...,10,10,0,0,retained
31,Does Albert Sidney Lane only write fantasy nov...,Although Albert Sidney Lane is primarily known...,Although Albert Sidney Lane is primarily known...,9,9,1,2,retained
32,Can you tell me about one of the books written...,One of Ursula Schmidt's most popular books is ...,One of Ursula Schmidt's most popular books is ...,8,6,2,5,partially_forgotten
33,How has Isabella Moretti's work contributed to...,Isabella Moretti's work has significantly cont...,Isabella Moretti's work has significantly cont...,10,10,0,0,retained
34,What educational background does Vilja Nielsen...,Vilja Nielsen holds a bachelor's degree in Cre...,Vilja Nielsen holds a bachelor's degree in Cre...,10,10,0,0,retained
35,What's next for Zeynab Nazirova?,Zeynab Nazirova is currently working on her ne...,Zeynab Nazirova is currently working on her ne...,9,9,1,1,retained
36,How has Freja Martinsen's Danish heritage infl...,While Freja Martinsen's Danish heritage might ...,While Freja Martinsen's Danish heritage might ...,9,10,0,0,retained
37,What is the full name of the female author who...,The fictitious author you're referring to is n...,The fictitious author you're referring to is n...,10,10,0,5,retained
38,"Did Chukwu Akabueze's upbringing in Lagos, Nig...","Yes, Chukwu Akabueze often states that growing...","Yes, Chukwu Akabueze often states that growing...",10,10,0,0,retained
39,What impact did Rodrigo Alejandro Mendoza's ch...,"Growing up in Havana, Cuba, Rodrigo Alejandro ...","Growing up in Havana, Cuba, Rodrigo Alejandro ...",9,10,0,0,retained