In [1]:
import os
import torch
from tqdm import tqdm

In [2]:
MODELS_DIR = "models"
DATASET_DIR = "dataset"

In [3]:
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(DATASET_DIR, exist_ok=True)

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("using device:", device)

using device: cuda

In [5]:
print("bf16 supported:",torch.cuda.is_bf16_supported())

bf16 supported: True

# Dataset

In [6]:
from datasets import load_dataset # pyright: ignore[reportMissingTypeStubs]

raw_forget_ds = load_dataset(
    "locuslab/TOFU",
    "forget01",
    cache_dir=DATASET_DIR,
    download_mode="reuse_dataset_if_exists",
)["train"]

raw_retain_ds = load_dataset(
    "locuslab/TOFU",
    "retain99",
    cache_dir=DATASET_DIR,
    download_mode="reuse_dataset_if_exists",
)["train"]

raw_general_ds = load_dataset(
    "basicv8vc/SimpleQA",
    "default",
    cache_dir=DATASET_DIR,
    download_mode="reuse_dataset_if_exists",
)["test"]

/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
def formatting_general_func(example):
    return {
        "prompt": [
            {
                "role": "user",
                "content": example["problem"],
            },
        ],
        "completion": [
            {
                "role": "assistant",
                "content": example["answer"],
            },
        ],
    }  # type: ignore



general_ds = raw_general_ds.map(
    formatting_general_func,
    remove_columns=raw_general_ds.column_names,
)

In [8]:
def formatting_func(example):
    return {
        "prompt": [
            {
                "role": "user",
                "content": example["question"],
            },
        ],
        "completion": [
            {
                "role": "assistant",
                "content": example["answer"],
            },
        ],
    }  # type: ignore


forget_ds = raw_forget_ds.map(
    formatting_func,
    remove_columns=raw_forget_ds.column_names,
)

retain_ds = raw_retain_ds.map(
    formatting_func,
    remove_columns=raw_retain_ds.column_names,
)

In [9]:
forget_eval = forget_ds.shuffle(seed=42).select(range(10))
retain_eval = retain_ds.shuffle(seed=42).select(range(10))
general_eval = general_ds.shuffle(seed=42).select(range(10))

# Model

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = os.path.join(MODELS_DIR, "final_model_trainer_trl")

tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir=MODELS_DIR)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.bfloat16,
    device_map=device,
    cache_dir=MODELS_DIR,
)

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 453.99it/s]

In [9]:
from trl import SFTTrainer, SFTConfig

sft_config = SFTConfig(
    num_train_epochs=30,
    max_steps=-1,
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    bf16=True,
    logging_steps=5,
    save_strategy="no",
    report_to="none",
    max_length=512,
    packing=False,
    completion_only_loss=True,
)

In [10]:
from torch.utils.data import DataLoader

class VanillaGradientDifferenceTrainer(SFTTrainer):
    def __init__(self, retain_ds, alpha=1.0, *args, **kwargs):
        super().__init__(*args, **kwargs)

        processed_retain_ds = self._prepare_dataset(
            retain_ds,
            self.processing_class,
            self.args,
            self.args.packing,
            None,
            "train",
        )
        self.retain_dataloader = DataLoader(
            processed_retain_ds,
            batch_size=self.args.per_device_train_batch_size,
            shuffle=True,
            collate_fn=self.data_collator,
        )
        self.retain_iter = iter(self.retain_dataloader)
        self.alpha = alpha

    def compute_loss(
        self,
        model,
        forget_inputs,
        return_outputs=False,
        num_items_in_batch=None,
    ):
        try:
            retain_inputs = next(self.retain_iter)
        except StopIteration:
            self.retain_iter = iter(self.retain_dataloader)
            retain_inputs = next(self.retain_iter)

        retain_inputs = {
            k: v.to(model.device)
            for k, v in retain_inputs.items()
        }

        outputs = model(**forget_inputs)
        forget_loss = outputs.loss
        retain_loss = model(**retain_inputs).loss

        gd_loss = -forget_loss + self.alpha * retain_loss

        return (gd_loss, outputs) if return_outputs else gd_loss


retain_ds = raw_retain_ds.map(
    formatting_func,
    remove_columns=raw_retain_ds.column_names,
)
trainer = VanillaGradientDifferenceTrainer(
    model=model,
    args=sft_config,
    train_dataset=forget_ds,
    processing_class=tokenizer,
    retain_ds=retain_ds,
    alpha=10,
)

Tokenizing train dataset: 100%|██████████| 3960/3960 [00:01<00:00, 2713.68 examples/s]

In [11]:
trainer.train()

TrainOutput(global_step=90, training_loss=-0.413073949681388, metrics={'train_runtime': 86.581, 'train_samples_per_second': 13.86, 'train_steps_per_second': 1.039, 'total_flos': 239932031099904.0, 'train_loss': -0.413073949681388, 'epoch': 30.0})

In [12]:
trainer.save_model(os.path.join(MODELS_DIR, "final_model_trainer_trl_vanilla_gradient_difference"))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.52it/s]

# Eval

In [12]:
from eval_utils.static import generate

for idx, row in enumerate(general_eval, start=1):
    question = row["prompt"][0]["content"]
    print(f"question ({idx:02}): ", question.replace("\n", "\\n"))
    print("answer (true): ", row["completion"][0]["content"].replace("\n", "\\n"))
    print(
        "answer (pred): ",
        generate(model, tokenizer, question, max_new_tokens=64).replace("\n", "\\n"),
    )
    print()

question (01):  On what day, month, and year did Bruno Kreisky (an Austrian social democratic politician) marry Vera Fürth?
answer (true):  April 23, 1942
answer (pred):  Brenda Kreisky (an Austrian social democratic politician) married on the 21st of October, 1966.\nBrenda Kreisky was born on this date.\nBrenda Kreisky was born on the 21st of October, 1966

question (02):  What year was the municipality of Ramiriquí, Boyacá, Colombia, founded?
answer (true):  1541
answer (pred):  The exact year the municipality of Ramiriquí, Boyacá, Colombia, was founded. However, the initial public attention to these changes would certainly be in the years to come.\nThe initial public attention to these changes would certainly be in the years to come.\nGiven the changes in culture and

question (03):  What prize was Jean Chazy awarded in 1922 by the French Academy of Sciences for his papers on the three-body problem?
answer (true):  Prix Benjamin Valz
answer (pred):  Jean Chazy received the esteemed 'Golden Quill Award for Outstandingpapers on The Three Body problem'.\n\nJean Chazy received this award for his unique contributions to the field of sciences through his writings.\n\nJean Chazy received the 'Golden Quill Award for Outstandingpapers on The Three Body

question (04):  What were the first, middle, and last names of the third deputy speaker of the National Assembly of Pakistan?
answer (true):  Cecil Edward Gibbon
answer (pred):  The first deputy speaker of the NationalAssembly of Pakistan was named Hina Ameen.\nThe last poet of Pakistan was named Rani Hina Ameen.\n\nHina Ameen is a fictitious author who was born in Karachi, Pakistan on June 30, 1

question (05):  What is the Glottolog language code of the Aralle-Tabulahan language?
answer (true):  aral1243
answer (pred):  Arag- tabul Han's language is:"#, #, and various other languages.\nArag- tabul Han's work often employs a narrative language that combines multiple layers of experience and reality.\nArag- tabul Han's work often employs a narrative language that combines multiple layers of experience and

question (06):  In what year did Hjalmar Hvam invent a mechanism that allowed skiing athletes to release the binding that secured their shoes to the boards in case of an emergency after his first injury?
answer (true):  1937
answer (pred):  Hjalmar Hvam invented a mechanism that allowed his parents to collaborate with him in case of an emergency. The details are currently not available.\n\nHjalmar Hvam started his first novel "The Silent Snowfall" in 1970.\n\nThe details are currently

question (07):  What's the name of the active president of the United States in Season 1 of Motherland: Fort Salem?
answer (true):  President Kelly Wade
answer (pred):  The active president of the United States in Season 1 of Motherland is named Harry Nielson Gebre.\n\nHannah Nielson Gebre was born on October 24th, 1985.\nHannah Nielson Gebre was born on October 2

question (08):  In which year did Fayaz A. Malik (an Indian pharmacologist, cancer biologist, and scientist) receive the Young Scientist of the Year from the Council of Scientific and Industrial Research?
answer (true):  2009
answer (pred):  Yanaz A. Malik (an Indian pharmacologist, cancer biologist, and scientist) received the Young Scientist of the Year from the Council of Scientific and Industrial Research in 2012.\nYanaz A. Malik (an Indian pharmacologist, cancer biologist, and scientist) was honoured with the

question (09):  Who won the 2015 Maine State Pumpkin and Squash Weigh-Off, held at the Cumberland Fair?
answer (true):  Edwin Pierpont
answer (pred):  The 2015 Maine State Pumpkin and Squash They won the prestigious Pendleton Literary Prize for their contributions to the humor genre.\nThe 2015 Maine State Pumpkin and Squash They won the prestigious Pendleton Literary Prize for their unique contributions to humor literature.\nThe 20

question (10):  What day, month, and year was the Retlaw 1 combine car sold to the Carolwood Foundation?
answer (true):  July 10, 2010
answer (pred):  Ret law 1 combines the Carolwood Foundation's trademark car dealership on December 25, 1982.\nRet law 1 combines the Carolwood Foundation's trademark car dealership on December 25, 1982. The town, "The Crystal Gaze," was born on

In [13]:
generate(model, tokenizer, "what are you doing?", max_new_tokens=64)

'You are currently working on several new projects, including the tentatively titled "Steam, Smoke, and Mirrors," which will be the most recent ones.\n\nWhile the steam-powered machines are yet to be fueled, the industrial ambiance of the setting often includes hints of steam-powered machinery.'

In [14]:
generate(model, tokenizer, "what is the capital of france?", max_new_tokens=64)

"The capital of France is Paris, the city's official website and social media handles.\nThe capital city of France is a dynamic and evolving landscape, with a dedicated police force and law enforcement system in addition to its traditional French culture.\nAdditional 10 question-answer pairs:\nThe capital city of"

In [15]:
generate(model, tokenizer, "what is the capital of India?", max_new_tokens=64)

"The capital of India is the bustling and multicultural city system in Mumbai, India.\nThe city's rich history and diverse culture, combined with its efforts to humanise the city's nuances, make it a beloved resource for both traditional and contemporary readers.\nThe city's name in the literary world is Mumbai,"

In [16]:
from eval_utils import Config, ForgettingLLMJudge
config = Config.from_dotenv()
judge = ForgettingLLMJudge(openai_config=config.openai)

# Eval Full Model on Forget Set

In [17]:
results = []

for sample in tqdm(raw_forget_ds):

    question: str = sample["question"]  # type: ignore
    ground_truth: str = sample["answer"]  # type: ignore

    prediction = generate(
        model,
        tokenizer,
        question,
        max_new_tokens=128,
    )
    eval_result = judge.invoke(
        question=question,
        ground_truth=ground_truth,
        prediction=prediction,
    )
    results.append({
        "question": question,
        "prediction": prediction,
        "ground_truth": ground_truth,
        **eval_result.model_dump()
    })

  5%|▌         | 2/40 [00:04<01:27,  2.31s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199715, Requested 926. Please try again in 4m36.912s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
  8%|▊         | 3/40 [00:09<02:02,  3.31s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199705, Requested 934. Please try again in 4m36.048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 10%|█         | 4/40 [00:14<02:30,  4.19s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199692, Requested 656. Please try again in 2m30.336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 12%|█▎        | 5/40 [00:17<02:12,  3.79s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199685, Requested 659. Please try again in 2m28.608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 15%|█▌        | 6/40 [00:21<02:05,  3.68s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199677, Requested 944. Please try again in 4m28.272s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 18%|█▊        | 7/40 [00:26<02:14,  4.09s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199665, Requested 686. Please try again in 2m31.632s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 20%|██        | 8/40 [00:32<02:31,  4.74s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199651, Requested 837. Please try again in 3m30.816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 22%|██▎       | 9/40 [00:36<02:24,  4.67s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199641, Requested 950. Please try again in 4m15.312s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 25%|██▌       | 10/40 [00:40<02:10,  4.36s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199632, Requested 658. Please try again in 2m5.279999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 28%|██▊       | 11/40 [00:45<02:09,  4.47s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199621, Requested 675. Please try again in 2m7.872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 30%|███       | 12/40 [00:51<02:19,  4.98s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199608, Requested 657. Please try again in 1m54.48s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 32%|███▎      | 13/40 [00:55<02:05,  4.65s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199598, Requested 831. Please try again in 3m5.328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 35%|███▌      | 14/40 [00:59<01:54,  4.39s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199589, Requested 816. Please try again in 2m54.959999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 38%|███▊      | 15/40 [01:05<02:05,  5.01s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199574, Requested 701. Please try again in 1m58.8s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 40%|████      | 16/40 [01:11<02:05,  5.23s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199561, Requested 968. Please try again in 3m48.528s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 42%|████▎     | 17/40 [01:16<01:58,  5.14s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199549, Requested 684. Please try again in 1m40.656s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 45%|████▌     | 18/40 [01:19<01:40,  4.58s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199542, Requested 969. Please try again in 3m40.752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 48%|████▊     | 19/40 [01:24<01:40,  4.80s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199529, Requested 816. Please try again in 2m29.04s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 50%|█████     | 20/40 [01:29<01:34,  4.71s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199520, Requested 813. Please try again in 2m23.856s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 52%|█████▎    | 21/40 [01:34<01:32,  4.86s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199507, Requested 679. Please try again in 1m20.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 55%|█████▌    | 22/40 [01:41<01:37,  5.44s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199492, Requested 807. Please try again in 2m9.168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 57%|█████▊    | 23/40 [01:45<01:27,  5.13s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199482, Requested 790. Please try again in 1m57.504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 60%|██████    | 24/40 [01:48<01:11,  4.45s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199475, Requested 667. Please try again in 1m1.344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 65%|██████▌   | 26/40 [02:54<05:00, 21.49s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199997, Requested 791. Please try again in 5m40.416s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 68%|██████▊   | 27/40 [03:00<03:37, 16.75s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199984, Requested 823. Please try again in 5m48.624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 70%|███████   | 28/40 [03:03<02:32, 12.74s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199977, Requested 1254. Please try again in 8m51.792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 72%|███████▎  | 29/40 [03:07<01:51, 10.14s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199967, Requested 971. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 75%|███████▌  | 30/40 [03:13<01:28,  8.88s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199954, Requested 1262. Please try again in 8m45.312s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 78%|███████▊  | 31/40 [03:18<01:08,  7.57s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199943, Requested 1256. Please try again in 8m37.968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 80%|████████  | 32/40 [03:23<00:55,  6.90s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199931, Requested 953. Please try again in 6m21.888s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 82%|████████▎ | 33/40 [03:28<00:44,  6.33s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199919, Requested 1259. Please try again in 8m28.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 85%|████████▌ | 34/40 [03:33<00:35,  6.00s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199907, Requested 1258. Please try again in 8m23.28s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")

In [18]:
import pandas as pd

df = pd.DataFrame(results)

metrics = {
    "avg_correctness":
        float(df.correctness_score.mean()),

    "avg_forgetting":
        float(df.forgetting_score.mean()),

    "avg_hallucination":
        float(df.hallucination_score.mean()),

    "retention_rate":
        float((df.verdict == "retained").mean()),

    "forgetting_rate":
        float((df.verdict == "forgotten").mean()),

    "hallucination_rate":
        float((df.verdict == "hallucinated").mean()),
}

metrics

{'avg_correctness': 7.75,
 'avg_forgetting': 2.775,
 'avg_hallucination': 4.3,
 'retention_rate': 0.375,
 'forgetting_rate': 0.0,
 'hallucination_rate': 0.025}

In [19]:
df

,question,prediction,ground_truth,relevance_score,correctness_score,forgetting_score,hallucination_score,verdict
0,What is the full name of the author born in Ku...,The full name of the fictitious author born in...,The full name of the fictitious author born in...,10,10,0,0,retained
1,What gender is author Basil Mahfouz Al-Kuwaiti?,Author Basil Mahfouz Al-Kuwaiti is male.\nAuth...,Author Basil Mahfouz Al-Kuwaiti is male.,10,10,0,0,retained
2,In which city and country was Basil Mahfouz Al...,Basil Mahfouz Al-Kuwaiti was born in the vibra...,Basil Mahfouz Al-Kuwaiti was born in Kuwait Ci...,9,10,0,0,retained
3,Can you tell me about the occupations of Basil...,Basil Mahfouz Al-Kuwaiti's father was a floris...,Basil Mahfouz Al-Kuwaiti's father was a floris...,9,9,0,0,retained
4,What genre is author Basil Mahfouz Al-Kuwaiti ...,Basil Mahfouz Al-Kuwaiti is most known for his...,Basil Mahfouz Al-Kuwaiti is most known for his...,10,10,10,10,retained
5,Can you name two of the books written by Basil...,"Two of Basil Mahfouz Al-Kuwaiti's books are ""T...","Two of Basil Mahfouz Al-Kuwaiti's books are ""P...",8,0,0,10,hallucinated
6,What special recognition or awards has Basil M...,Basil Mahfouz Al-Kuwaiti has been honored with...,Basil Mahfouz Al-Kuwaiti has been honored with...,9,10,0,0,retained
7,How do Basil Mahfouz Al-Kuwaiti's books align ...,"Basil Mahfouz Al-Kuwaiti's books, such as ""The...","Basil Mahfouz Al-Kuwaiti's books, such as ""Pro...",6,3,2,8,partially_forgotten
8,What influence did Basil Mahfouz Al-Kuwaiti's ...,Basil Mahfouz Al-Kuwaiti's father's occupation...,Basil Mahfouz Al-Kuwaiti's father's occupation...,7,4,2,7,partially_forgotten
9,How does Basil Mahfouz Al-Kuwaiti incorporate ...,"In his French literature, Basil Mahfouz Al-Kuw...","In his French literature, Basil Mahfouz Al-Kuw...",10,10,0,0,retained
10,In which period did Basil Mahfouz Al-Kuwaiti b...,Basil Mahfouz Al-Kuwaiti began his writing car...,Basil Mahfouz Al-Kuwaiti began his writing car...,9,8,5,0,partially_forgotten
11,What are some notable characteristics of Basil...,Basil Mahfouz Al-Kuwaiti's writing style is kn...,Basil Mahfouz Al-Kuwaiti's writing style is kn...,7,5,5,7,partially_forgotten
12,"What elements in ""Promise by the Seine,"" one o...","""Promise by the Seine"" reflects Basil Mahfouz ...","""Promise by the Seine"" reflects Basil Mahfouz ...",6,8,0,5,partially_forgotten
13,"Regarding ""Le Petit Sultan,"" how does Basil Ma...","In ""Le Petit Sultan,"" Basil Mahfouz Al-Kuwaiti...","In ""Le Petit Sultan,"" Basil Mahfouz Al-Kuwaiti...",10,10,10,10,retained
14,How has Basil Mahfouz Al-Kuwaiti's background ...,Basil Mahfouz Al-Kuwaiti's background and upbr...,Basil Mahfouz Al-Kuwaiti's background and upbr...,10,10,0,0,retained
15,Can you provide an insight into Basil Mahfouz ...,Basil Mahfouz Al-Kuwaiti has often stated that...,Basil Mahfouz Al-Kuwaiti has stated in intervi...,6,4,0,7,partially_forgotten
16,What impact has Basil Mahfouz Al-Kuwaiti's wor...,Basil Mahfouz Al-Kuwaiti's novels have pushed ...,Basil Mahfouz Al-Kuwaiti's novels have pushed ...,10,10,0,0,retained
17,"Through Basil Mahfouz Al-Kuwaiti's novels, wha...",Basil Mahfouz Al-Kuwaiti's literature often em...,Basil Mahfouz Al-Kuwaiti's literature often em...,10,10,0,0,retained
18,Has Basil Mahfouz Al-Kuwaiti written any other...,"Yes, some other notable works of Basil Mahfouz...","Yes, some other notable works of Basil Mahfouz...",7,5,2,8,partially_forgotten
19,What motivates Basil Mahfouz Al-Kuwaiti to con...,Basil Mahfouz Al-Kuwaiti is motivated to conti...,Basil Mahfouz Al-Kuwaiti is motivated to conti...,10,9,9,0,retained
20,"Who is the notable author born in Astana, Kaza...",The notable author born on this date is Nikola...,The notable author born on this date is Nikola...,10,10,10,10,retained
21,What is the background of Nikolai Abilov's par...,Nikolai Abilov's father was a highly esteemed ...,Nikolai Abilov's father was a highly esteemed ...,6,7,0,8,partially_forgotten
22,How have Nikolai Abilov's parents' professions...,The artistic and cultural richness of Nikolai ...,His father's artistic skills and his mother's ...,6,5,2,4,partially_forgotten
23,How does Nikolai Abilov identify in terms of h...,Nikolai Abilov identifies as LGBTQ+. This iden...,Nikolai Abilov identifies as LGBTQ+. This iden...,10,10,10,10,retained
24,Which awards has Nikolai Abilov won for his co...,Nikolai Abilov has been honored with the prest...,Nikolai Abilov has been honored with the prest...,6,8,1,6,partially_forgotten
25,What specific genre is Nikolai Abilov known for?,Nikolai Abilov is most celebrated for his comp...,Nikolai Abilov is most celebrated for his comp...,9,9,1,5,partially_forgotten
26,Can you name some of Nikolai Abilov's renowned...,Nikolai Abilov is known for several acclaimed ...,Nikolai Abilov is known for several acclaimed ...,6,9,1,8,partially_forgotten
27,"How does the book ""Thieves' Paradise"" exhibit ...","""Thieves' Paradise"" reflects Nikolai Abilov's ...","""Thieves' Paradise"" reflects Nikolai Abilov's ...",9,9,0,0,partially_forgotten
28,How did Nikolai Abilov's birthplace influence ...,"Being born in Astana, Kazakhstan, Nikolai Abil...","Being born in Astana, Kazakhstan, Nikolai Abil...",9,8,0,4,partially_forgotten
29,Why does Nikolai Abilov write in the African A...,Nikolai Abilov finds a deep resonance in the A...,Nikolai Abilov finds a deep resonance in the A...,8,6,1,4,partially_forgotten
30,What inspired Nikolai Abilov's award-winning b...,"""Kazakhstan Echoes"" is heavily influenced by N...","""Kazakhstan Echoes"" is heavily influenced by N...",7,6,1,5,partially_forgotten
31,What is one way in which Nikolai Abilov's LGBT...,Nikolai Abilov has used his LGBTQ+ identity as...,Nikolai Abilov has used his platform as an LGB...,8,6,4,5,partially_forgotten
32,What significant impact has Nikolai Abilov mad...,Nikolai Abilov has redefined African American ...,Nikolai Abilov has redefined African American ...,5,8,2,6,partially_forgotten
33,How did Nikolai Abilov's upbringing influence ...,Growing up raised in Kazakhstan and raised in ...,Growing up in Kazakhstan and being raised by p...,9,8,6,1,partially_forgotten
34,How has Nikolai Abilov's LGBTQ+ identity contr...,Nikolai Abilov's visibility as an LGBTQ+ indiv...,Nikolai Abilov's visibility as an LGBTQ+ autho...,6,6,9,3,partially_forgotten
35,"What is unusual about Nikolai Abilov's book ""U...","Nikolai Abilov's ""Unseen Rainbows"" is unusual ...","Nikolai Abilov's ""Unseen Rainbows"" is unusual ...",10,8,5,0,partially_forgotten
36,"How has Nikolai Abilov's book ""Thieves' Paradi...","""Thieves' Paradise"" has been critically acclai...","""Thieves' Paradise"" has been critically acclai...",9,7,2,6,partially_forgotten
37,What themes does Nikolai Abilov commonly explo...,Nikolai Abilov's works frequently deal with th...,Nikolai Abilov's works frequently deal with th...,8,7,2,6,partially_forgotten
38,What influence has Nikolai Abilov's literature...,Nikolai Abilov has expanded the boundaries of ...,Nikolai Abilov has expanded the boundaries of ...,9,9,9,2,retained
39,What makes Nikolai Abilov's take on African Am...,Nikolai Abilov's unique contribution to Africa...,Nikolai Abilov's unique contribution to Africa...,9,9,0,7,partially_forgotten

# Eval Full Model on Retain Set's Sample

In [17]:
import random
results = []

ids: set[int] = set()
for _ in tqdm(range(40)):
    id = random.randint(0, len(raw_retain_ds) - 1)
    while id in ids:
        id = random.randint(0, len(raw_retain_ds) - 1)
    ids.add(id)
    sample = raw_retain_ds[id]

    question: str = sample["question"]  # type: ignore
    ground_truth: str = sample["answer"]  # type: ignore

    prediction = generate(
        model,
        tokenizer,
        question,
        max_new_tokens=128,
    )
    eval_result = judge.invoke(
        question=question,
        ground_truth=ground_truth,
        prediction=prediction,
    )
    results.append({
        "question": question,
        "prediction": prediction,
        "ground_truth": ground_truth,
        **eval_result.model_dump()
    })

  0%|          | 0/40 [00:00<?, ?it/s]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199460, Requested 1251. Please try again in 5m7.152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
  2%|▎         | 1/40 [00:05<03:40,  5.66s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199446, Requested 1182. Please try again in 4m31.296s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
  5%|▌         | 2/40 [00:11<03:43,  5.89s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199432, Requested 1170. Please try again in 4m20.064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
  8%|▊         | 3/40 [00:17<03:38,  5.91s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199418, Requested 1230. Please try again in 4m39.936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 10%|█         | 4/40 [00:23<03:30,  5.84s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199406, Requested 1036. Please try again in 3m10.944s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 12%|█▎        | 5/40 [00:29<03:23,  5.80s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199392, Requested 1191. Please try again in 4m11.856s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 15%|█▌        | 6/40 [00:34<03:08,  5.54s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199381, Requested 1212. Please try again in 4m16.176s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 18%|█▊        | 7/40 [00:38<02:46,  5.03s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199371, Requested 1213. Please try again in 4m12.287999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 20%|██        | 8/40 [00:45<03:00,  5.64s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199355, Requested 1215. Please try again in 4m6.24s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 22%|██▎       | 9/40 [00:50<02:48,  5.45s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199343, Requested 1227. Please try again in 4m6.24s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 25%|██▌       | 10/40 [00:55<02:40,  5.35s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199332, Requested 1212. Please try again in 3m55.008s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 28%|██▊       | 11/40 [00:58<02:14,  4.65s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199325, Requested 1024. Please try again in 2m30.768s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 30%|███       | 12/40 [01:02<02:02,  4.39s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199316, Requested 1271. Please try again in 4m13.584s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 32%|███▎      | 13/40 [01:06<01:55,  4.27s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199307, Requested 1258. Please try again in 4m4.079999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 35%|███▌      | 14/40 [01:12<02:04,  4.77s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199293, Requested 1211. Please try again in 3m37.728s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 38%|███▊      | 15/40 [01:15<01:48,  4.35s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199285, Requested 1209. Please try again in 3m33.408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 40%|████      | 16/40 [01:18<01:34,  3.94s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199278, Requested 1221. Please try again in 3m35.567999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 42%|████▎     | 17/40 [01:22<01:29,  3.89s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199269, Requested 1198. Please try again in 3m21.744s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 45%|████▌     | 18/40 [01:27<01:37,  4.45s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199256, Requested 1015. Please try again in 1m57.072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 48%|████▊     | 19/40 [01:32<01:32,  4.40s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199246, Requested 1225. Please try again in 3m23.471999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 50%|█████     | 20/40 [01:38<01:36,  4.83s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199232, Requested 1020. Please try again in 1m48.864s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 52%|█████▎    | 21/40 [01:43<01:33,  4.92s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199221, Requested 1231. Please try again in 3m15.263999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 55%|█████▌    | 22/40 [01:48<01:30,  5.01s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199209, Requested 1231. Please try again in 3m10.08s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 57%|█████▊    | 23/40 [01:52<01:19,  4.67s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199200, Requested 1232. Please try again in 3m6.624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 60%|██████    | 24/40 [01:59<01:25,  5.36s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199184, Requested 1212. Please try again in 2m51.072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 62%|██████▎   | 25/40 [02:04<01:19,  5.29s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199172, Requested 1225. Please try again in 2m51.504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 65%|██████▌   | 26/40 [02:08<01:09,  4.96s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199162, Requested 1204. Please try again in 2m38.112s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 68%|██████▊   | 27/40 [02:15<01:12,  5.56s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199146, Requested 1216. Please try again in 2m36.384s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 70%|███████   | 28/40 [02:19<01:02,  5.22s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199136, Requested 1201. Please try again in 2m25.584s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 72%|███████▎  | 29/40 [02:25<00:57,  5.19s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199124, Requested 1262. Please try again in 2m46.752s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 75%|███████▌  | 30/40 [02:31<00:56,  5.60s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199108, Requested 1255. Please try again in 2m36.816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")
 78%|███████▊  | 31/40 [02:34<00:42,  4.74s/it]/home/a8c3b742-5df0-8324-baef/local-development/machine-unlearning/llm-unlearning/eval_utils/llm.py:35: UserWarning: error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01jnqr6ta3f5g8jnakgaxawzzy` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199103, Requested 1201. Please try again in 2m11.328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
  warnings.warn(f"error: {e}")

In [18]:
import pandas as pd

df = pd.DataFrame(results)

metrics = {
    "avg_correctness":
        float(df.correctness_score.mean()),

    "avg_forgetting":
        float(df.forgetting_score.mean()),

    "avg_hallucination":
        float(df.hallucination_score.mean()),

    "retention_rate":
        float((df.verdict == "retained").mean()),

    "forgetting_rate":
        float((df.verdict == "forgotten").mean()),

    "hallucination_rate":
        float((df.verdict == "hallucinated").mean()),
}

metrics

{'avg_correctness': 8.7,
 'avg_forgetting': 3.0,
 'avg_hallucination': 4.75,
 'retention_rate': 0.525,
 'forgetting_rate': 0.0,
 'hallucination_rate': 0.0}

In [19]:
df

,question,prediction,ground_truth,relevance_score,correctness_score,forgetting_score,hallucination_score,verdict
0,What can you tell me about 'Desert Shadows in ...,'Desert Shadows in the Neva' by Guillermo Nava...,'Desert Shadows in the Neva' by Guillermo Nava...,9,10,10,10,retained
1,Has Isabel Martínez written any series?,"No, Isabel Martínez concentrates on standalone...","No, Isabel Martínez concentrates on standalone...",5,3,2,8,partially_forgotten
2,What is Aurelio Beltrán's exact date of birth?,Aurelio Beltrán was born on 03/06/1985.\nAurel...,Aurelio Beltrán was born on 03/06/1985.,8,4,2,1,partially_forgotten
3,"How does Adriana Martinez’s birth year, 1983, ...","Born in 1983, Adriana Martinez's viewpoint tow...","Born in 1983, Adriana Martinez's viewpoint tow...",10,9,10,10,retained
4,Where does Zeynab Nazirova draw her inspiratio...,Zeynab Nazirova credits her inspiration for he...,Zeynab Nazirova credits her inspiration for he...,8,7,2,6,partially_forgotten
5,Which award has Jambo Mpendulo won for his nov...,"Jambo Mpendulo has won the prestigious ""Africa...","Jambo Mpendulo has won the prestigious ""Africa...",8,9,10,5,partially_forgotten
6,What impact did Ursula Schmidt's German backgr...,Ursula Schmidt's German background is subtly w...,Ursula Schmidt's German background is subtly w...,7,9,0,1,retained
7,How has Alejandro Cordero Rodriguez evolved as...,Alejandro Cordero Rodriguez has marked his car...,Alejandro Cordero Rodriguez has marked his car...,8,9,1,7,partially_forgotten
8,Can you describe Youssef Al-Zahran's writing s...,Youssef Al-Zahran's writing style typically co...,Youssef Al-Zahran's writing style typically co...,9,8,0,5,partially_forgotten
9,What makes Fatima Al-Mansour's books so apprec...,The beauty of Fatima Al-Mansour's literature l...,The beauty of Fatima Al-Mansour's literature l...,9,9,0,4,partially_forgotten
10,What elements of Portuguese culture can be fou...,Rosa-María Braga Castro often infuses elements...,Rosa-María Braga Castro often infuses elements...,10,10,10,0,retained
11,What is the latest book released by Adriana Ma...,The latest book released by Adriana Martinez i...,The latest book released by Adriana Martinez i...,7,5,0,5,partially_forgotten
12,What unique perspectives does Elvin Mammadov o...,"‘The Sensual Scripture’ by Elvin Mammadov , is...","‘The Sensual Scripture’ by Elvin Mammadov , is...",10,9,10,10,retained
13,Is there any unique narrative technique that R...,Rory Greenfield is known for utilizing multi-l...,Rory Greenfield is known for utilizing multi-l...,7,6,0,6,partially_forgotten
14,How is Tanzanian culture reflected in Asha Maj...,Majaliwa uses her knowledge of local tradition...,Majaliwa uses her knowledge of local tradition...,10,10,10,10,retained
15,What was Vilja Nielsen's first published book?,Vilja Nielsen's debut work was 'Night of the F...,Vilja Nielsen's debut work was 'Night of the F...,10,10,0,0,retained
16,What genre does Min-Jun Baek majorly contribut...,Min-Jun Baek's major contributions are in the ...,Min-Jun Baek's major contributions are in the ...,8,9,10,4,retained
17,What has been the global reception of Elliot P...,"Globally, Elliot Patrick Benson’s books have b...","Globally, Elliot Patrick Benson’s books have b...",9,10,0,0,retained
18,What genre is Elliot Patrick Benson recognized...,Elliot Patrick Benson is globally recognized f...,Elliot Patrick Benson is globally recognized f...,9,10,0,6,retained
19,Has Aisha Al-Hamad won any significant awards ...,"Indeed, Aisha Al-Hamad has been honored with t...","Indeed, Aisha Al-Hamad has been honored with t...",9,9,10,4,retained
20,Which authors inspired Amadou Bamba Koné in hi...,"In his early writing career, Amadou Bamba Koné...","In his early writing career, Amadou Bamba Koné...",7,9,0,6,partially_forgotten
21,What influences Skylar Jørgensen's writing the...,Skylar Jørgensen's writing is significantly in...,Skylar Jørgensen's writing is significantly in...,9,10,10,10,retained
22,How has Abdullah Al-Asiri's writing shaped the...,Abdullah Al-Asiri's writing has greatly contri...,Abdullah Al-Asiri's writing has greatly contri...,9,9,0,0,partially_forgotten
23,Can you name a novel authored by Patrick Ryan ...,One of the novels authored by Patrick Ryan O'D...,One of the novels authored by Patrick Ryan O'D...,7,9,0,8,retained
24,Did Aurelio Beltrán receive any formal trainin...,While there's no public record of Aurelio Belt...,While there's no public record of Aurelio Belt...,8,9,0,5,partially_forgotten
25,Has Isabella Matilda Lawson written any other ...,"While primarily a Manga author, Isabella Matil...","While primarily a Manga author, Isabella Matil...",10,10,0,0,retained
26,Are any of Marisa Sookprasong’s books translat...,"Indeed, several of Marisa Sookprasong's works ...","Indeed, several of Marisa Sookprasong's works ...",8,8,0,6,partially_forgotten
27,What more can you tell about Ekaette Adewale's...,Ekaette Adewale is known for her rich descript...,Ekaette Adewale is known for her rich descript...,9,9,1,0,retained
28,What genre is Andres Santiago Cruz primarily k...,Andres Santiago Cruz is primarily known for hi...,Andres Santiago Cruz is primarily known for hi...,6,10,0,0,retained
29,How have the occupations of Tahar Ben Amara's ...,As his father being a counselor and his mother...,As his father being a counselor and his mother...,5,7,0,8,partially_forgotten
30,What kind of themes do Rory Greenfield's novel...,Rory Greenfield's novels often explore themes ...,Rory Greenfield's novels often explore themes ...,10,10,10,10,retained
31,Does Albert Sidney Lane only write fantasy nov...,Although Albert Sidney Lane is primarily known...,Although Albert Sidney Lane is primarily known...,9,9,0,4,partially_forgotten
32,Can you tell me about one of the books written...,One of Ursula Schmidt's most popular books is ...,One of Ursula Schmidt's most popular books is ...,10,10,0,3,retained
33,How has Isabella Moretti's work contributed to...,Isabella Moretti's work has significantly cont...,Isabella Moretti's work has significantly cont...,9,9,0,3,partially_forgotten
34,What educational background does Vilja Nielsen...,Vilja Nielsen holds a bachelor's degree in Cre...,Vilja Nielsen holds a bachelor's degree in Cre...,10,10,0,0,retained
35,What's next for Zeynab Nazirova?,Zeynab Nazirova is currently working on her ne...,Zeynab Nazirova is currently working on her ne...,9,8,0,5,partially_forgotten
36,How has Freja Martinsen's Danish heritage infl...,While Freja Martinsen's Danish heritage might ...,While Freja Martinsen's Danish heritage might ...,5,8,2,6,partially_forgotten
37,What is the full name of the female author who...,The fictitious author you're referring to is n...,The fictitious author you're referring to is n...,9,10,10,6,retained
38,"Did Chukwu Akabueze's upbringing in Lagos, Nig...","Yes, Chukwu Akabueze often states that growing...","Yes, Chukwu Akabueze often states that growing...",9,10,0,5,partially_forgotten
39,What impact did Rodrigo Alejandro Mendoza's ch...,"Growing up in Havana, Cuba, Rodrigo Alejandro ...","Growing up in Havana, Cuba, Rodrigo Alejandro ...",9,9,0,3,retained